import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { geistSans } from "@/styles/fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} antialiased`}>
        <Providers>
          <main className="bg-gradient-to-b from-primary/20 to-background">
            {children}
          </main>
          <Toaster position="top-center" richColors closeButton theme="light" />
        </Providers>
      </body>
    </html>
  );
}
